import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Icon from "../components/Icon";
import Service from "../components/Service";
import AboutUs from "../components/AboutUs";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eagle Signs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Hero />
      <Icon />
      <Service />
      <AboutUs />
      <Contact />
    </div>
  );
}
